function [avgCovar, avgCovarPhase, avgPLS, avgPlsPhase, avgWpli, allCovar,...
    allCovarPhase, allPLS, allPlsPhase, allWpli] = ...
    expLagLead(eegfile, timefile, freqbands, channels,uniqtypes)

% Modified by Margaret Cunniff from lagedf5 (Sept 2017)
% Generates covariation, PLS, and WPLI measures
% Outputs both average values for given trial type & all values computed
% for each individual trial


% making array where each column is time point, first row is starts, second
% row is stops, third row is type
fid = fopen(timefile);
timepts = fscanf(fid, '%f', [3,inf]);

ntypes = length(uniqtypes);
ntrials = size(timepts,2);
nbands = size(freqbands,1);
nchannels = length(channels);
nelpairs = nchannels*(nchannels-1)/2;
elpairs = zeros(nelpairs,2);

% initialize summary arrays - average of all trials for a given condition
avgPLS = zeros(nelpairs, ntypes, nbands);
avgPlsPhase = zeros(nelpairs, ntypes, nbands);
avgCovar = zeros(nelpairs,ntypes, nbands);
avgCovarPhase = zeros(nelpairs,ntypes, nbands);
avgWpli = zeros(nelpairs, ntypes, nbands);

% Individual data points for every trial analyzed
allCovar = cell(nelpairs, ntypes,nbands);
allCovarPhase = cell(nelpairs, ntypes,nbands);
allPLS = cell(nelpairs,ntypes,nbands);
allPlsPhase = cell(nelpairs,ntypes,nbands);
allWpli = cell(nelpairs,ntypes,nbands);

% first read in all the data
[data, header] = readedf5(eegfile);

channel1 = data{1, channels(1)};
channel2 = data{1, channels(2)};

% check if data are the same size. if not, downsample larger one.
if length(channel1) == length(channel2)
    delt = header.duration / header.nsamples(channels(1));
    
elseif length(channel1) > length(channel2)
    factor = length(channel1)/length(channel2);
    data{1,channels(1)} = downsample(channel1,factor);
    delt = header.duration / header.nsamples(channels(2));
    
elseif length(channel2) > length(channel1)
    factor = length(channel2)/length(channel1);
    data{1,channels(2)} = downsample(channel2,factor);
    delt = header.duration / header.nsamples(channels(1));
end

if size(data{1, channels(1)}) ~= size(data{1, channels(2)})
    msg = 'Data still not equal, downsampling failed';
    error(msg)
end


% delt = header.duration / header.nsamples(channels(1));

% Event - individual entry for each calculation made - for each trial,
% events for every freq band/electrode pair/type
event = 0;
covar = [];
covarPhase = [];
pls = [];
plsphase = [];
wpli = [];

for ch1IDX=1:length(channels),
    for ch2IDX=1+ch1IDX:length(channels),
        % stepping through all possible electrode pairs, 
        for bandIDX=1:nbands,
            % individual calculations for each frequency band
            fmin = freqbands(bandIDX,1);
            fmax = freqbands(bandIDX,2);
            for trialIDX = 1:ntrials,
                % Stepping through each trail from time file
                start = round(timepts(1,trialIDX)/delt); % converting start & stop to sample numbers
                stop = round(timepts(2,trialIDX)/delt);
                
                % Throw error if times invalid or too small for analysis
                % min length determined by length needed to create filter
                minEventLength = ceil(3*(1/fmin)/delt+1);
                
                if start < 1 || stop > length(data{channels(ch1IDX)}),
                    disp('Time outside bounds of data')
                    break;
                elseif stop-start < minEventLength, 
                    disp('Event smaller than sampling window')
                    disp(stop-start)
                    break;
                end
                
                % create reference arrays for each event with electrode
                % IDs, frequency band, and segment type
                event = event + 1; 
                
                % Event # acts as index
                el1(event) = channels(ch1IDX) ;% which channel is assigned as el1
                el2(event) = channels(ch2IDX); % which channel is assigned as el2
                freqband(event) = bandIDX; % which frequency band is analyzed
                type(event) = timepts(3,trialIDX); % what type is the segment
                el1_data = data{channels(ch1IDX)}(start:stop);
                el2_data = data{channels(ch2IDX)}(start:stop);
                
                [covar(event),covarPhase(event),pls(event),plsphase(event),wpli(event)] = ...
                    trialLagLead(el1_data,el2_data,delt,fmin,fmax);
            end
        end
    end
end

try 
    length(el1);
catch
    error('No data generated by trialLagLead.')
end

% Now have several large vectors containing all of data and reference information
% Organizing into summary/output tables
elpair = 0;
for ch1IDX=1:length(channels),
    for ch2IDX=ch1IDX+1:length(channels),
        elpair = elpair+1;
        for bandIDX=1:nbands,
            for typeIDX=1:ntypes,
                % which electrode pair is being analyzed
                elpairs(elpair,:) = [ch1IDX ch2IDX];
                % find all values matching current electrodes, band, and
                % type
                findTrials = find(el1 == channels(ch1IDX) & el2 == channels(ch2IDX) & freqband == bandIDX & type == uniqtypes(typeIDX));
                if isempty(findTrials),
                    disp('No trials of that type.')
                    disp([ch1IDX, ch2IDX, bandIDX, typeIDX])
                    break;
                end
                
                % go through all the trials of that type and add them to
                % summary vectors for average values
                for trials=1:length(findTrials),
                    avgCovar(elpair,typeIDX, bandIDX) = avgCovar(elpair,typeIDX,bandIDX) + covar(findTrials(trials));
                    avgCovarPhase(elpair,typeIDX, bandIDX) = avgCovarPhase(elpair,typeIDX,bandIDX) + covarPhase(findTrials(trials));
                    avgPLS(elpair,typeIDX, bandIDX) = avgPLS(elpair,typeIDX, bandIDX) + pls(findTrials(trials));
                    avgWpli(elpair,typeIDX, bandIDX) = avgWpli(elpair,typeIDX, bandIDX) + wpli(findTrials(trials)) ;
                    avgPlsPhase(elpair,typeIDX, bandIDX) = avgPlsPhase(elpair,typeIDX, bandIDX) + plsphase(findTrials(trials));
                end
                
                % Divide summed values by number of trials of that type for
                % individual mean for each condition 
                avgCovar(elpair, typeIDX, bandIDX) = avgCovar(elpair,typeIDX,bandIDX) / length(findTrials);
                avgPLS(elpair, typeIDX, bandIDX) = avgPLS(elpair,typeIDX,bandIDX) / length(findTrials);
                avgWpli(elpair, typeIDX, bandIDX) = avgWpli(elpair,typeIDX,bandIDX) / length(findTrials);
                avgPlsPhase(elpair,typeIDX, bandIDX) = avgPlsPhase(elpair,typeIDX, bandIDX) + plsphase(findTrials(trials));
                
                % add all individual values to cell arrays containing all
                % data
                for trials=1:length(findTrials),
                    allCovar{elpair,typeIDX, bandIDX} = [allCovar{elpair,typeIDX, bandIDX}, covar(findTrials(trials))];
                    allCovarPhase{elpair,typeIDX, bandIDX} = [allCovarPhase{elpair,typeIDX, bandIDX}, covarPhase(findTrials(trials))];
                    allPLS{elpair,typeIDX, bandIDX} = [allPLS{elpair,typeIDX, bandIDX}, pls(findTrials(trials))];
                    allPlsPhase{elpair,typeIDX, bandIDX} = [allPlsPhase{elpair,typeIDX, bandIDX}, plsphase(findTrials(trials))];
                    allWpli{elpair,typeIDX, bandIDX} = [allWpli{elpair,typeIDX, bandIDX}, wpli(findTrials(trials))];
                end
            end
        end
    end
end